name: interactive_timeline
description: A performant, reusable horizontal timeline widget with LOD ticks, panning, anchored zoom, and customizable markers/ticks.
version: 0.2.1

homepage: https://mim-armand.github.io/Dynamic-Timeline/
repository: https://github.com/mim-Armand/Dynamic-Timeline
issue_tracker: https://github.com/mim-Armand/Dynamic-Timeline/issues

topics:
  - timeline
  - widget
  - zoom
  - visualization
  - charts

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.22.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: false

