title: Interactive Timeline
version: 0.2.1
description: A performant, reusable horizontal timeline widget for Flutter with anchored zoom, panning, and auto-LOD ticks.
theme: minima
show_downloads: false
github_repo_url: https://github.com/mim-Armand/Dynamic-Timeline
google_analytics: 

# Build settings
markdown: kramdown
highlighter: rouge

